In [ ]:
!pip install numpy

In [1]:
import numpy as np

### Numpy:Introduction

- NumPy is a Open Source Python package. It stands for **Numerical Python**. It is a library consisting of multidimensional array objects and a collection of routines for processing of array.

- NumPy is the fundamental package for scientific computing with Python , having following important functionalities: 
     - A powerful N-dimensional array object
     - A sophisticated (broadcasting) functions
     - Contains tools for integrating C/C++ and Fortran code
     - Have  useful  linear algebra, Fourier transform, and random number capabilities

### Why NuMpy?

- Mathematical and logical operations on **arrays**.

- Efficient storage and manipulation of **numerical arrays** is which is fundamental in  the process of  **data science**.

- NumPy arrays form the core of nearly the entire **ecosystem** of **data science** tools in Python,

In [2]:
## Arrays are homogeneous (same data type)

In [ ]:
## It is a table of elements (typically numbers),all of the similar type, indexed by a tuple of positive integers

In [3]:
### NumPy's array class is know as ndarray.Even , it is known by the alias array

In [4]:
import time as tm

size_1 = 10000000

def pure_python_version():
    start_time_pp =  tm.time() ## time of start of code execution
    list1 = range(size_1)
    list2 = range(size_1)
    sum_list=[list1[i]+list2[i] for i in range(len(list1))]
    end_time_pp =  tm.time()
    return end_time_pp - start_time_pp ## end time for execution (difference)

def numpy_version():
    start_time_np = tm.time()
    array1 = np.arange(size_1)
    array2 =  np.arange(size_1)
    sum_array = array1 + array2
    end_time_np = tm.time()
    return end_time_np - start_time_np ## end time for execution (difference)

python_time = pure_python_version()
numpy_time  = numpy_version()

print("pure python version=",python_time)
print("numpy =",numpy_time)

pure python version= 2.8661367893218994
numpy = 0.033350229263305664


In [5]:
a =(1,2,3,4,5)

print(a)

(1, 2, 3, 4, 5)


In [6]:
b= np.array(a)
print(b)

[1 2 3 4 5]


In [8]:
type(a)

tuple

In [9]:
type(b)

numpy.ndarray

In [10]:
b.shape

(5,)

In [11]:
b.size

5

In [12]:
b.ndim

1

In [73]:
a10 = np.array([1, 2, 3, 7, 5, 1], ndmin = 10) 
print (a)
np.ndim(a)

[[[[[[[[[[1 2 3 7 5 1]]]]]]]]]]


10

In [14]:
a = np.array([1, 2, 3], dtype = complex) 
print (a)

[1.+0.j 2.+0.j 3.+0.j]


In [15]:
array_2 = [[1,2,3],[4,5,6],[7,8,9]]
array_3= np.array(array_2)
array_3
type(array_3)

numpy.ndarray

In [16]:
array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
array_3.shape

(3, 3)

In [18]:
array_3.size

9

In [19]:
array_3.ndim

2

In [20]:
array_3[2] 

array([7, 8, 9])

In [21]:
array_3[1, 2] 

6

In [22]:
array_3[:, 2] 

array([3, 6, 9])

In [23]:
array_3[:, 1]

array([2, 5, 8])

In [24]:
array_3[1,:]

array([4, 5, 6])

In [25]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(10,100, 10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [27]:
np.arange(100, 10, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [28]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [29]:
np.zeros(9,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [32]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [33]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [34]:
np.eye(3,3) # Identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.eye(3,4) # Identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [37]:
np.linspace(0,4,10) # (start,end,no of values)

array([0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778,
       2.22222222, 2.66666667, 3.11111111, 3.55555556, 4.        ])

In [38]:
np.linspace(1.23,4.7,10)

array([1.23      , 1.61555556, 2.00111111, 2.38666667, 2.77222222,
       3.15777778, 3.54333333, 3.92888889, 4.31444444, 4.7       ])

In [39]:
np.linspace(-2,2,10)

array([-2.        , -1.55555556, -1.11111111, -0.66666667, -0.22222222,
        0.22222222,  0.66666667,  1.11111111,  1.55555556,  2.        ])

In [43]:
np.random.rand(20)

array([0.02331116, 0.55952984, 0.24199043, 0.72675409, 0.12538699,
       0.45062167, 0.51731814, 0.68054271, 0.94505862, 0.13650429,
       0.34025016, 0.48122397, 0.91082328, 0.63791707, 0.06384056,
       0.44886197, 0.7413382 , 0.51664682, 0.14879389, 0.46664379])

In [46]:
np.random.rand(2,5)

array([[0.5269133 , 0.79756094, 0.23652215, 0.47323781, 0.3205158 ],
       [0.79170014, 0.25772925, 0.31201865, 0.28216979, 0.04150347]])

In [47]:
array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
array_3.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [50]:
array_3.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [51]:
x=[[1,2,3,4],[4,5,6,7],[7,8,9,10],[10,11,12,13]]
x=np.array(x)
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [52]:
x.min() ## overrall minimum

1

In [53]:
x.max()

13

In [55]:
x.mean()

7.0

In [56]:
x.std()

3.5355339059327378

In [57]:
x.var()

12.5

In [58]:
x.sum()

112

In [59]:
x.min(axis=0) ## minimum value column wise

array([1, 2, 3, 4])

In [60]:
x.min(axis=1) 

array([ 1,  4,  7, 10])

In [61]:
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [62]:
x.mean(axis= 1)

array([ 2.5,  5.5,  8.5, 11.5])

In [63]:
x.argmin() ## index of the minimum value 

0

In [65]:
x.argmax() 

15

In [66]:
x.argmin(axis=0) #column wise

array([0, 0, 0, 0], dtype=int64)

In [67]:
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [68]:
x.flatten() #2D to 1D

array([ 1,  2,  3,  4,  4,  5,  6,  7,  7,  8,  9, 10, 10, 11, 12, 13])

In [75]:
a10.flatten()

array([1, 2, 3, 7, 5, 1])

In [76]:
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [77]:
x.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12],
       [ 4,  7, 10, 13]])

In [ ]:
x = 0-10
x1 = 10-100
x2 = 100-1000
x3 = 1000-10000

In [78]:
#x
7/10000

0.0007

In [79]:
#x1
37/10000

0.0037

In [80]:
#x2
890/10000

0.089

In [81]:
#x3
9999/10000

0.9999

In [83]:
np.random.rand(4,2)

array([[0.49437407, 0.77541857],
       [0.48135894, 0.97894769],
       [0.44601894, 0.04184456],
       [0.05636819, 0.7411898 ]])

In [88]:
np.random.randint(2,7, 4)

array([6, 4, 5, 5])

In [91]:
np.random.randn(3,3)

array([[-1.96126003,  0.78260465,  0.01196919],
       [ 0.36096105, -0.06005139,  0.79430791],
       [ 0.53463191,  1.8774928 ,  0.49398567]])

In [92]:
np.random.pareto(x)

array([[0.06390046, 0.62423838, 0.0258483 , 0.02587372],
       [0.03876023, 0.04002416, 0.89645402, 0.12098019],
       [0.00236744, 0.20538802, 0.00112896, 0.03299691],
       [0.02563755, 0.01084192, 0.0714311 , 0.06431188]])

In [93]:
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [94]:
np.around(10.8756)

11.0

In [95]:
np.pi

3.141592653589793