In [1]:
import numpy as np

In [2]:
A = np.array([ [4, 10, 11], [21, 22, 23], [31, 32, 33] ])
B = np.ones((3,3))
print(A)

[[ 4 10 11]
 [21 22 23]
 [31 32 33]]


In [4]:
A

array([[ 4, 10, 11],
       [21, 22, 23],
       [31, 32, 33]])

In [5]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
print("Adding to arrays: ")
print(A + B)

Adding to arrays: 
[[ 5. 11. 12.]
 [22. 23. 24.]
 [32. 33. 34.]]


In [7]:
print("Substracting Two Arrays")
print(A-B)

Substracting Two Arrays
[[ 3.  9. 10.]
 [20. 21. 22.]
 [30. 31. 32.]]


In [8]:
print("\nMultiplying two arrays: ")
print(A * B)


Multiplying two arrays: 
[[ 4. 10. 11.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [9]:
print("Multiplying one Array with scalar")
print(3*A)

Multiplying one Array with scalar
[[12 30 33]
 [63 66 69]
 [93 96 99]]


In [10]:
print("Matrix Multiplication")
print(np.dot(A,B))

Matrix Multiplication
[[25. 25. 25.]
 [66. 66. 66.]
 [96. 96. 96.]]


In [11]:
A

array([[ 4, 10, 11],
       [21, 22, 23],
       [31, 32, 33]])

In [12]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.sqrt(A)

array([[2.        , 3.16227766, 3.31662479],
       [4.58257569, 4.69041576, 4.79583152],
       [5.56776436, 5.65685425, 5.74456265]])

In [14]:
np.square(A)

array([[  16,  100,  121],
       [ 441,  484,  529],
       [ 961, 1024, 1089]])

In [15]:
A

array([[ 4, 10, 11],
       [21, 22, 23],
       [31, 32, 33]])

In [16]:
np.exp(A)

array([[5.45981500e+01, 2.20264658e+04, 5.98741417e+04],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09],
       [2.90488497e+13, 7.89629602e+13, 2.14643580e+14]])

In [17]:
np.log(A)

array([[1.38629436, 2.30258509, 2.39789527],
       [3.04452244, 3.09104245, 3.13549422],
       [3.4339872 , 3.4657359 , 3.49650756]])

In [18]:
a = np.array([0,30,45,60,90]) 
print(a)
print ('Sine of different angles:' )

[ 0 30 45 60 90]
Sine of different angles:


In [19]:
a

array([ 0, 30, 45, 60, 90])

In [20]:
# Convert to radians by multiplying with pi/180 
print (np.sin(a*np.pi/180) )
print ("\n") 

[0.         0.5        0.70710678 0.8660254  1.        ]




In [21]:
print ('Cosine values for angles in array:')
print (np.cos(a*np.pi/180) )
print ("\n") 

Cosine values for angles in array:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]




In [22]:
print ('Tangent values for given angles:' )
print (np.tan(a*np.pi/180) )

Tangent values for given angles:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [23]:
a=np.array([[11.667,23.662],[33.21,45.887]])
print (np.around(a)) 

[[12. 24.]
 [33. 46.]]


In [24]:
a

array([[11.667, 23.662],
       [33.21 , 45.887]])

In [25]:
print (np.around(a, decimals = 2))

[[11.67 23.66]
 [33.21 45.89]]


In [26]:
A

array([[ 4, 10, 11],
       [21, 22, 23],
       [31, 32, 33]])

In [27]:
A.sum() 

187

In [28]:
A.sum(axis = 1) 

array([25, 66, 96])

In [29]:
A.sum(axis = 0) 

array([56, 64, 67])

In [33]:
A=[[1,2,3],[3,4,5]]
B=[[3,3,4],[1,2,0]]
a=np.array(A)
b=np.array(B)


In [31]:
A

[[1, 2, 3], [3, 4, 5]]

In [32]:
B

[[3, 3, 4], [1, 2, 0]]

In [34]:
np.greater_equal(a,b)

array([[False, False, False],
       [ True,  True,  True]])

In [36]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [37]:
a[:,1] 

array([2, 4])

In [40]:
a[:,1] = 3

In [41]:
a

array([[1, 3, 3],
       [3, 3, 5]])

In [ ]:
subset1 = a[:,1] = 2.5

In [42]:
a

array([[1, 3, 3],
       [3, 3, 5]])

In [43]:
b

array([[3, 3, 4],
       [1, 2, 0]])

In [44]:
np.concatenate([a,b])

array([[1, 3, 3],
       [3, 3, 5],
       [3, 3, 4],
       [1, 2, 0]])

In [45]:
"python" + "java"

'pythonjava'

In [46]:
np.concatenate([a,b],axis=1)

array([[1, 3, 3, 3, 3, 4],
       [3, 3, 5, 1, 2, 0]])

In [47]:
np.concatenate([a,b],axis=0)

array([[1, 3, 3],
       [3, 3, 5],
       [3, 3, 4],
       [1, 2, 0]])